const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const out = process.env.CHECK_OUTPUT || path.join(__dirname, 'content-check');
fs.mkdirSync(out, {recursive:true});
const url = process.env.SITE_URL || 'http://localhost:5179/';
const report = { url, checkedAt:new Date().toISOString(), errors:[], failures:[], httpErrors:[], consoleErrors:[], checks:[] };
(async () => {
  const browser = await chromium.launch({channel:'chrome', headless:true, args:['--enable-unsafe-webgpu']});
  async function enter(page) {
    page.on('console', msg => { if (msg.type()==='error') report.consoleErrors.push(msg.text()); });
    page.on('response', response => { if(response.status()>=400) report.httpErrors.push({url:response.url(),status:response.status()}); });
    page.on('pageerror', error => { report.errors.push(error.stack); console.log('PAGE ERROR', error.message); });
    page.on('requestfailed', req => report.failures.push({url:req.url(),error:req.failure()}));
    await page.goto(url, {waitUntil:'domcontentloaded',timeout:90000});
    await page.waitForFunction(() => !document.querySelector('#momo-enter').disabled, null, {timeout:180000});
    await page.locator('#momo-enter').click();
    await page.waitForFunction(() => window.__playable, null, {timeout:180000});
    await page.waitForTimeout(1600);
  }
  async function tab(page, name) {
    await page.locator(`[data-profile-tab="${name}"]`).click();
    assert.equal(await page.locator(`[data-profile-panel="${name}"]`).isVisible(), true);
    assert.equal(await page.locator('[data-profile-tab][aria-selected="true"]').count(), 1);
    await page.waitForTimeout(250);
  }
  async function screenshot(page,name) { await page.screenshot({path:path.join(out, name+'.png')}); }
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  await enter(page);
  await page.locator('.momo-dock [data-momo-action="home"]').click();
  await page.waitForTimeout(500);
  await screenshot(page,'desktop-about');
  assert.match(await page.locator('.home-content').innerText(), /某大模型公司/);
  await tab(page,'career');
  assert.equal(await page.locator('.momo-career-stop').count(), 6);
  await screenshot(page,'desktop-career');
  await page.locator('.home-content').evaluate(el => el.scrollTop = el.scrollHeight);
  await screenshot(page,'desktop-career-end');
  await tab(page,'projects');
  assert.equal(await page.locator('.momo-project-group').count(), 3);
  assert.equal(await page.locator('.momo-project-card').count(), 5);
  await screenshot(page,'desktop-projects');
  await page.locator('.home-content').evaluate(el => el.scrollTop = 600);
  await screenshot(page,'desktop-skills');
  await page.locator('.home-content').evaluate(el => el.scrollTop = 1100);
  await screenshot(page,'desktop-multi-agent');
  await page.locator('.home-content').evaluate(el => el.scrollTop = el.scrollHeight);
  await screenshot(page,'desktop-code-agent');
  assert.equal(await page.locator('#momo-panel-projects a[href="https://momozi.cc/"]').count(),1);
  await tab(page,'connect');
  await screenshot(page,'desktop-accounts');
  await page.evaluate(() => Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value => {window.__copiedAccount=value}}}));
  await page.locator('#momo-panel-connect [data-copy-account]').first().click();
  await page.waitForFunction(() => window.__copiedAccount === 'momo子讲AI');
  assert.match(await page.locator('#momo-panel-connect [data-copy-status]').innerText(),/已复制/);
  // Denied clipboard + failed legacy fallback must never claim success.
  await page.evaluate(() => { navigator.clipboard.writeText=async()=>{throw Error('denied')}; document.execCommand=()=>false; });
  await page.locator('#momo-panel-connect [data-copy-account]').nth(1).click();
  await page.waitForTimeout(100);
  assert.match(await page.locator('#momo-panel-connect [data-copy-status]').innerText(),/无法自动复制/);
  await page.locator('[data-profile-tab="connect"]').focus();
  await page.keyboard.press('ArrowLeft');
  assert.equal(await page.locator('[data-profile-tab="projects"]').getAttribute('aria-selected'),'true');
  await page.keyboard.press('Home');
  assert.equal(await page.locator('[data-profile-tab="about"]').getAttribute('aria-selected'),'true');
  report.checks.push('desktop: all tabs, six career stops, five projects, source links, keyboard tabs, clipboard success + denied fallback');
  await page.keyboard.press('Escape'); await page.waitForTimeout(700);
  await page.locator('.momo-dock [data-momo-action="connect"]').click(); await page.waitForTimeout(500);
  assert.equal(await page.locator('.momo-contact-modal').isVisible(),true);
  assert.equal(await page.locator('.momo-contact-modal .momo-account').count(),3);
  await page.locator('.momo-contact-modal .momo-inline-actions a').focus();
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')), '关闭社交账号');
  await page.keyboard.press('Shift+Tab');
  assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('href')), 'https://momozi.cc/');
  await screenshot(page,'desktop-contact-modal');
  await page.locator('.momo-contact-modal .js-close').click(); await page.waitForTimeout(700);
  await page.locator('.momo-dock [data-momo-action="map"]').click(); await page.waitForTimeout(400);
  assert.equal(await page.locator('.modal.map').isVisible(),true);
  await page.keyboard.press('Escape'); await page.waitForTimeout(700);
  const before = await page.evaluate(() => ({...game.player.position}));
  await page.keyboard.down('w'); await page.waitForTimeout(900); await page.keyboard.up('w');
  const after = await page.evaluate(() => ({...game.player.position}));
  assert.ok(Math.hypot(after.x-before.x,after.z-before.z)>0.05,'car still moves');
  await page.locator('.momo-dock [data-momo-action="projects"]').click(); await page.waitForTimeout(4500);
  await page.evaluate(()=>game.world.areas.projects.open()); await page.waitForTimeout(3000);
  assert.equal(await page.evaluate(()=>game.world.areas.projects.navigation.current.attributes.role),'Coding Agent');
  await screenshot(page,'desktop-workshop');
  await page.keyboard.press('Escape'); await page.waitForTimeout(1000);
  report.checks.push('world: contact opens/closes; map and driving preserved; works shortcut and 3D project content preserved');
  await page.close();
  const mobile = await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
  await enter(mobile);
  await screenshot(mobile,'mobile-world');
  await mobile.locator('.momo-dock [data-momo-action="home"]').click(); await mobile.waitForTimeout(500);
  await screenshot(mobile,'mobile-about');
  for(const name of ['career','projects','connect']) {
    await tab(mobile,name);
    await screenshot(mobile,'mobile-'+name);
    const overflow = await mobile.locator('.momo-profile').evaluate(el=>({client:el.clientWidth,scroll:el.scrollWidth}));
    assert.ok(overflow.scroll<=overflow.client+1,`${name}: no horizontal overflow ${JSON.stringify(overflow)}`);
  }
  await mobile.locator('.js-menu .js-close').click(); await mobile.waitForTimeout(700);
  await mobile.locator('.momo-dock [data-momo-action="connect"]').click(); await mobile.waitForTimeout(500);
  await screenshot(mobile,'mobile-contact-modal');
  const modalBox=await mobile.locator('.momo-contact-modal').boundingBox();
  assert.ok(modalBox.x>=0 && modalBox.x+modalBox.width<=390 && modalBox.y>=0 && modalBox.y+modalBox.height<=844);
  await mobile.locator('.momo-contact-modal .js-close').click();await mobile.waitForTimeout(700);
  await mobile.setViewportSize({width:320,height:640});await mobile.waitForTimeout(700);
  const dockBox=await mobile.locator('.momo-dock').boundingBox();
  assert.ok(dockBox.x>=0 && dockBox.x+dockBox.width<=320, '320px dock fits');
  await mobile.locator('.momo-dock [data-momo-action="home"]').click();await mobile.waitForTimeout(500);
  await tab(mobile,'projects');await screenshot(mobile,'small-mobile-projects');
  const narrow=await mobile.locator('.momo-profile').evaluate(el=>({client:el.clientWidth,scroll:el.scrollWidth}));
  assert.ok(narrow.scroll<=narrow.client+1, '320px profile fits');
  report.checks.push('mobile: 390px + 320px layouts, all tabs, modal viewport bounds, no horizontal overflow');
  await browser.close();
  assert.equal(report.errors.length,0,'no page errors');
  assert.equal(report.httpErrors.length,0,'no HTTP errors');
  assert.equal(report.consoleErrors.length,0,'no console errors');
  assert.equal(report.failures.length,0,'no failed requests');
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
})().catch(error=>{report.testError=error.stack;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.error(error);process.exit(1)});
